### ISSUE TITLE
Change model name

### ISSUE THREAD

**Issue by felipebhz** [oleg-agapov/basic-spa-vue-firebase#4]
https://github.com/oleg-agapov/basic-spa-vue-firebase/blob/a9f0d8426c3e7c3a738753726d771c3a328ca003/src/components/Signup.vue#L40

**Line #40 should be:** `v-model="confirmPassword"`

**Comment by jgfoster** [comment]
Lines 40, 60, and 66 are all consistent and use passwordConfirm. This seems to work fine for me so I don't see the need for a change.

**Comment by oleg-agapov** [comment]
@felipebhz yeah, it's kinda not consistent with `id` and `name` of the field, but it doesn't break the app, so I would leave it as is. Of course, in your project you can use consistent naming, it's a good catch ;)
